### ISSUE TITLE
Matlab 2021a - marker creep with repeated triangulation

### ISSUE THREAD

**Issue by jmr137** [diegoaldarondo/Label3D#12] opened 2021-06-02 12:25 UTC
When using Matlab version 2021a repeated triangulation causes all labeled points to shift in one direction. For instance when running the exact same labeling job in Matlab 2020a, with the same version of Label3d, I can repeatedly triangulate a fully labeled mouse frame 40+ times and see no change in the pixel location of markers. However doing the exact same thing in Matlab 2021a results in all of my labeled points shifting by 20+ pixels. I still need to check if the creep in marker location has to do with the display, or if the shift is occurring in points3D due to something like a change in triangulateMultiview() or a drop in precision of how 2d points are being stored.

**Comment by diegoaldarondo** [comment] 2021-06-02 15:46
Hey James,

Thanks for bringing this up. Haven't tried testing in 2021a myself, but I can try to give it a look later this week. 

What OS are you using? There are sometimes differences in the CV toolbox between OSs.

**Comment by jmr137** [comment] 2021-06-02 18:08
Hi Diego,

I am using windows 10. Our lab is using 4 computers that have the exact same OS, hardware, and specs. The scripts were all run off the same programs stored in drop box, with the same dataset. The only major difference between computers I could think of was the Matlab version. By CV toolbox you mean the Matlab computer vision toolbox right? If that is the case the updated to the CV toolbox from 2020a to 2021a could be causing the problem. The issue isn't urgent because we can keep using 2020a, I just didn't want someone else to have to troubleshoot their calibration just to realize it was the Matlab version.

Thanks,

Jim
________________________________

**Comment by diegoaldarondo** [comment] 2021-06-09 14:44
Sorry for the delay, just got to this now. 

I can't replicate this behavior on my win10 system with the most recent Matlab 2021a using my own data. Triangulation works as in the previous versions. Repeated triangulation and  repeated single-view-weighted triangulation don't show any drift. 

I went through the documented changes in 2021a to the computer vision toolbox. They don't describe anything explicitly changing with multiview triangulation, although there are substantial updates to visual SLAM which might include undocumented changes to triangulation. 

Perhaps you can try again with the most recent 2021a (Update 2) and see if the problem persists. There are no published bug reports/fixes about this specific issue, but its possible that they just hasn't made them public.

**Comment by diegoaldarondo** [comment] 2021-06-24 16:17
Closing for now, since I can't reproduce the problem.

**Closed by diegoaldarondo** 2021-06-24 16:17 UTC
